# Usage of tidyr::gather

In [5]:
library(dplyr)
library(tidyr)
# From http://stackoverflow.com/questions/1181060

In [6]:
stocks <- tibble(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4)
)
stocks

   time       X          Y           Z
1  2009-01-01 -0.3916247  0.89298435 -1.75954795
2  2009-01-02  2.5419567 -2.00339137 -1.11442322
3  2009-01-03  1.3424158  1.89830064 -6.69547694
4  2009-01-04 -0.5390410 -2.20575651  7.50918899
5  2009-01-05 -0.1276458 -0.75133218 -2.42145448
6  2009-01-06  0.2427514 -1.08126082 -3.44809385
7  2009-01-07 -0.5662422 -2.28700310  7.11392397
8  2009-01-08  0.8161961 -1.71203773  3.66592355
9  2009-01-09 -1.2991576  1.11404811  0.05387812
10 2009-01-10 -0.5312403 -0.08148353 -2.47696103

## Approach 1

In [9]:
gather(stocks, stock, price, -time) %>% head()

  time       stock price
1 2009-01-01 X     -0.3916247
2 2009-01-02 X      2.5419567
3 2009-01-03 X      1.3424158
4 2009-01-04 X     -0.5390410
5 2009-01-05 X     -0.1276458
6 2009-01-06 X      0.2427514

## Approach 2

In [10]:
stocks %>% gather(stock, price, -time) %>% head()

  time       stock price
1 2009-01-01 X     -0.3916247
2 2009-01-02 X      2.5419567
3 2009-01-03 X      1.3424158
4 2009-01-04 X     -0.5390410
5 2009-01-05 X     -0.1276458
6 2009-01-06 X      0.2427514

In [4]:
# get first observation for each Species in iris data -- base R
mini_iris <- iris[c(1, 51, 101), ]
# gather Sepal.Length, Sepal.Width, Petal.Length, Petal.Width
gather(mini_iris, key = flower_att, value = measurement,
       Sepal.Length, Sepal.Width, Petal.Length, Petal.Width)
# same result but less verbose
gather(mini_iris, key = flower_att, value = measurement, -Species)

# repeat iris example using dplyr and the pipe operator
library(dplyr)
mini_iris <-
  iris %>%
  group_by(Species) %>%
  slice(1)
mini_iris %>% gather(key = flower_att, value = measurement, -Species)
# }

   time       stock price
1  2009-01-01 X      0.4298749
2  2009-01-02 X      0.7551751
3  2009-01-03 X      1.1933295
4  2009-01-04 X     -0.6251554
5  2009-01-05 X      0.5825103
6  2009-01-06 X      1.1168545
7  2009-01-07 X      1.3997000
8  2009-01-08 X     -0.3482335
9  2009-01-09 X      0.8044698
10 2009-01-10 X      0.2182939
11 2009-01-01 Y      0.8236092
12 2009-01-02 Y      2.4252098
13 2009-01-03 Y     -1.6130009
14 2009-01-04 Y     -1.1719634
15 2009-01-05 Y     -2.0820488
16 2009-01-06 Y      2.0508840
17 2009-01-07 Y      3.3179466
18 2009-01-08 Y      1.1867468
19 2009-01-09 Y      0.3004033
20 2009-01-10 Y     -0.7259499
21 2009-01-01 Z      1.2225171
22 2009-01-02 Z     -2.2196129
23 2009-01-03 Z     -1.1209942
24 2009-01-04 Z      0.4138083
25 2009-01-05 Z     -0.4136993
26 2009-01-06 Z      3.1723064
27 2009-01-07 Z     -1.1276172
28 2009-01-08 Z      4.1337929
29 2009-01-09 Z     -6.3708822
30 2009-01-10 Z      1.3673927

   time       stock price
1  2009-01-01 X      0.4298749
2  2009-01-02 X      0.7551751
3  2009-01-03 X      1.1933295
4  2009-01-04 X     -0.6251554
5  2009-01-05 X      0.5825103
6  2009-01-06 X      1.1168545
7  2009-01-07 X      1.3997000
8  2009-01-08 X     -0.3482335
9  2009-01-09 X      0.8044698
10 2009-01-10 X      0.2182939
11 2009-01-01 Y      0.8236092
12 2009-01-02 Y      2.4252098
13 2009-01-03 Y     -1.6130009
14 2009-01-04 Y     -1.1719634
15 2009-01-05 Y     -2.0820488
16 2009-01-06 Y      2.0508840
17 2009-01-07 Y      3.3179466
18 2009-01-08 Y      1.1867468
19 2009-01-09 Y      0.3004033
20 2009-01-10 Y     -0.7259499
21 2009-01-01 Z      1.2225171
22 2009-01-02 Z     -2.2196129
23 2009-01-03 Z     -1.1209942
24 2009-01-04 Z      0.4138083
25 2009-01-05 Z     -0.4136993
26 2009-01-06 Z      3.1723064
27 2009-01-07 Z     -1.1276172
28 2009-01-08 Z      4.1337929
29 2009-01-09 Z     -6.3708822
30 2009-01-10 Z      1.3673927

   Species    flower_att   measurement
1  setosa     Sepal.Length 5.1
2  versicolor Sepal.Length 7.0
3  virginica  Sepal.Length 6.3
4  setosa     Sepal.Width  3.5
5  versicolor Sepal.Width  3.2
6  virginica  Sepal.Width  3.3
7  setosa     Petal.Length 1.4
8  versicolor Petal.Length 4.7
9  virginica  Petal.Length 6.0
10 setosa     Petal.Width  0.2
11 versicolor Petal.Width  1.4
12 virginica  Petal.Width  2.5

   Species    flower_att   measurement
1  setosa     Sepal.Length 5.1
2  versicolor Sepal.Length 7.0
3  virginica  Sepal.Length 6.3
4  setosa     Sepal.Width  3.5
5  versicolor Sepal.Width  3.2
6  virginica  Sepal.Width  3.3
7  setosa     Petal.Length 1.4
8  versicolor Petal.Length 4.7
9  virginica  Petal.Length 6.0
10 setosa     Petal.Width  0.2
11 versicolor Petal.Width  1.4
12 virginica  Petal.Width  2.5

   Species    flower_att   measurement
1  setosa     Sepal.Length 5.1
2  versicolor Sepal.Length 7.0
3  virginica  Sepal.Length 6.3
4  setosa     Sepal.Width  3.5
5  versicolor Sepal.Width  3.2
6  virginica  Sepal.Width  3.3
7  setosa     Petal.Length 1.4
8  versicolor Petal.Length 4.7
9  virginica  Petal.Length 6.0
10 setosa     Petal.Width  0.2
11 versicolor Petal.Width  1.4
12 virginica  Petal.Width  2.5